import Head from 'next/head'
import Image from 'next/image'
import React, { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css'
import MovieData from './MovieData'
import Router, { useRouter } from 'next/router';
// import 'bootstrap/dist/css/bootstrap.css'; // Add this line
// import '../styles/globals.css'


export default function Home() {
  // const[text, setText] = useState("");
  const [query, setQuery] = useState('');
  const [movies, setMovies] = useState([]);
  const router = useRouter();

  // const movieValueChange = (val) => {
  //   setQuery(val);
  //   console.log(val);
  // };

  const searchMovies = async (e) => {
    e.preventDefault();
    // console.log(e);
    console.log("submitting");
  //const query = 'Jurassic Park';
    const url = `http://www.omdbapi.com/?s=${query}&apikey=2f079760`;
    // try {
    // console.log(url);
    const res = await fetch(url);
    // console.log(res);
    const data = await res.json();
    // console.log(data.Search);
    setMovies(data.Search);
    console.log(data.Search);
      
    //   console.log(url);
    //   const res = await fetch(url);
    //   const data = await res.json();
      // setMovies(data.results);
      // console.log(data).results;
    // } catch (err) {
    //   console.log(err)
    // }
  };

  // const openMovieDetailsPage = (MovieId) => {
  //   router.push(`/${MovieId}`);
  // };

  return (
    <div className='container'>
      <Head>
        <title>MovieSearch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container'>
        <h3 className='title'>Search Your Movie Here</h3>
        <form className='form' onSubmit={searchMovies}>
          <div className='container'>
            <label className='label' htmlFor='query'>Movie Name : </label>
            <input type={'text'} className='input' name='text' value={query} onChange={(e) => setQuery(e.target.value)} placeholder='Type Here'></input>
            <button type='submit' className='button SearchBtn btn btn-primary m-3' onClick={searchMovies}>Search</button>
          </div>
        </form>

        <div className='card-list'>
          <MovieData movies={movies} key={movies.imbdID}  />
          {/* {movies.map(movie => (
              // <h3 className='card--title'>{movie.title}</h3>
            <MovieData movies={movies} key={movie.imdbID} />
          ))} */}
        </div>

      </main>

    </div>
  )
}
